### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by robitsrl** [t00ks/homeassistant_webhook_proxy#4]
Hi,
I have create the addon but when i try to open the url i get HTTP ERROR 500.
The addon is up because if i change the in the url web_hook_proxy with web_hook_proxy2 i get HTTP ERROR 404

Do i need some lib to install to get it working ? I'm using HA OS with a raspberry hardware.

that's what i get in the log:

Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN3I86IDSGRQ", Request id "0HN3I86IDSGRQ:00000002": An unhandled exception was thrown by the application.
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at web_hook_proxy.Controllers.WebProxyController.Get(String hookName) in /src/Controllers/WebProxyController.cs:line 20
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by robitsrl** [comment]
if from the code i remote thw following the request is done:

 WebRequest request = WebRequest.Create($"https://{LOCAL_IPADDRESS}:8123/api/webhook/{hookName}");
            request.Method = "POST";
            WebResponse response = request.GetResponse();

my HA istance is accessibile only with ssl but without the following code i can reach the webserver.

How can then i talk to HA to trigger something ?

Thank's

**Comment by robitsrl** [comment]
WebRequest request = WebRequest.Create($"https://{LOCAL_IPADDRESS}:8123/api/webhook/{hookName}");
            request.Method = "POST";
            WebResponse response = request.GetResponse();
